import Head from "next/head";
import React from "react";

const DefaultLayout = ({
  title,
  children,
}: {
  title: string;
  children: any;
}) => {
  return (
    <React.Fragment>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {children}
      </main>
    </React.Fragment>
  );
};

export default DefaultLayout;
